### ISSUE TITLE
Wrong parameter for exception

### ISSUE THREAD

**Issue by selossevianney** [UniAlteri/sellsy-client#1]
Everytime you throw an exception, you use the wrong parameter to get the error message. 
Exemple line 378:Client.php You give the parameter $answer->error instead of $answer->error->mesage. I have no time now to make a pull request so can you ,please, fix it ? 

Sorry for my pretty bad english, hope you understood my request :)

This come from the sellsy api doc : 
API error message - The response is JSON formatted, so you have the status in the JSON response: status: error and error: {{error_message}}
{"response":null,"error":{"code":"E_IO_MODE_DONT_EXIST","message":"IO_MODE jsone doest not exist","more":"jsone"},"status":"error"}

**Comment by frenchcomp** [comment]
Hi,
It's fixed. But, originally the client checked "$answer->error->mesage" but for several errors catched in some projects, $answer->error was a string and not an object. I never knew this scenario.

So, now the client can manage this two cases.

Thanks for your feedback :)

Richard.
