### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by kewix** [UniAlteri/sellsy-client#10]
Bonjour l'équipe Teknoo !

Sur sellsy j'ai souvent l'erreur ci-dessous quand je synchronise les stocks par exemple. D'après la doc il n'y a pas moyen de faire la synchronisation de tous les produits en une seule fois, il faut donc faire produit par produit et je pense qu'il y a une limite sur le nombre de requetes.

Mon code fait $sellsy->Catalogue()->getList() puis pour chaque résultat $sellsy->Stock()->getForItem().

Severity: error --> Exception: Client error: `POST https://apifeed.sellsy.com/0/` resulted in a `401 Unauthorized` response:

Est-ce que vous avez une solution pour synchroniser les stocks et pour cette erreur 401 ?

Merci d'avance !

**Comment by frenchcomp** [comment]
Bonjour,
Désolé pour le temps de réponse, j'avais pris une semaine de repos avec une coupure des moyens de communications.

En ce qui concerne votre erreur, le problème provient de l'api Sellsy elle-même et non de la bibliothèque. Malheureusement on a très peu de retour de la part de l'équipe technique Sellsy et aucun support de leur part, aucun compte de test. On maintient juste la bibliothèque car elle est utilisé, mais uniquement grâce au retour des utilisateurs.

Pour votre problème, c'est du traitement par lot, je vous invite à l'exécuter via une tâche programmée (tâche cron) et d'y ajouter une temporisation entre chaque appel pour ne pas atteindre la limite. Ou encore récupérer une seule fois la liste des stocks, la stocker et puis la traiter un petit lot, séparé dans le temps.

La bibliothèque ne peut prendre en charge une telle problématique car elle doit être gérée directement par votre code et elle ne peut faire des suppositions pour avoir un comportement correct sur toutes les installations.

**Comment by kewix** [comment]
Bonjour,

Merci pour la réponse, je comprends tout à fait votre situation ! Peut-être
que vous avez certaines informations plus précises que ce qu'on peut
obtenir de la part de sellsy ?
Quel est le nombre de requêtes max à ne pas dépasser et en combien de temps
? Quelle délai de temporisation utiliser ?

Pour les stocks, nous y avions réfléchi et le problème c'est que nous
voulons les stocks pour un warehouse donné, et il n'y pas de méthodes (à
notre connaissance) pour faire ceci. Si vous avez des informations non
documentées nous sommes preneurs !

Merci pour la réponse et bonne journée.


Mike.

2018-05-14 8:48 GMT+02:00 Richard Déloge <notifications@github.com>:

**Comment by frenchcomp** [comment]
Rebonjour,
Désolé, je n'ai aucune informations à ce sujet. Comme dit précédemment, je n'ai aucun contact avec l'équipe technique de Sellsy, juste eu par le passé un contact commercial qui c'est contenté de redirigé mes réponses vers le service technique.. sans réponse également. 

J'ai autant d'informations que vous, celle publiquement disponible sur leurs sites internet.

J'ai malheureusement pas plus d'informations à ce sujet.

**Comment by eewee** [comment]
Bonjour,

Si besoin vous pouvez créer un compte "trial" sur [Sellsy.fr](https://sellsy.fr), vous permettant de tester notre API (sandbox).
En cas de questions / interrogations, n'hésitez pas à écrire sur [contact@sellsy.com](mailto:contact@sellsy.com) (en indiquant dans le sujet "Question API").

La préconisation de  "@frenchcomp" est justifiée : 

> "Pour votre problème, c'est du traitement par lot, je vous invite à l'exécuter via une tâche programmée (tâche cron) et d'y ajouter une temporisation entre chaque appel pour ne pas atteindre la limite. 
Ou encore récupérer une seule fois la liste des stocks, la stocker et puis la traiter un petit lot, séparé dans le temps."

@frenchcomp : N'hésitez pas à me contacter directement pour toutes questions sur l'API.

**Comment by frenchcomp** [comment]
Merci @eewee pour votre retour, je n'hésiterais pas à vous contacter à l'occasion. 

J'ai déjà utilisé un compte trial en décembre 17/janvier 18 pour traiter un autre bug, cette solution fonctionne bien effet. :)

Bonne soirée
Richard

@kewix, Bonjour, du coup, suite aux réponses par mail et à ce ticket, je ferme l'issue. Je vais ajouter dans la todo list une meilleure prise en charge (si possible) des excès d'appel à l'api afin de mieux informer le développeur des modifications à apporter à sa solution.

Bonne soirée,
