### ISSUE TITLE
Supplier getList error

### ISSUE THREAD

**Issue by clecocq** [UniAlteri/sellsy-client#14]
Hello,

I'm not able to make this work with your library

`return $this->sellsyClient->get()->Supplier()->getList(['pagination'=>['nbperpage'=>$nbPerpage, 'pagenum'=>$pageNum]])->getResponse();`

I'm using exactly the same with clients and it's working, but in the case of suppliers it's not. I cannot find if the error comes from your library or from sellsy. 

`Teknoo\Sellsy\Client\Exception\ErrorException  : Plugin support is not loaded`

Thank you in advance,

Cyril

**Comment by frenchcomp** [comment]
Hello,
ErrorException are thrown only when the server returns an error. (The message comes from Sellsy). Wthen the failure comes from the library, or the transport (guzzle or other), the exception is of type RequestFailureException.

Have a nice day.

**Comment by clecocq** [comment]
Hey,

After much investigations, there's a typo here : https://github.com/TeknooSoftware/sellsy-client/blob/master/definitions/Supplier.php#L48 

It should be "Supplier" and not "Support".

Thanks,

**Comment by frenchcomp** [comment]
A patch has been released. 2.0.5. It's fine for you?

**Comment by clecocq** [comment]
Hey perfect thank you

**Comment by frenchcomp** [comment]
Thanks for the feed back. Happy new year
