### ISSUE TITLE
email is invalid when creating new client

### ISSUE THREAD

**Issue by Ericdev89** [UniAlteri/sellsy-client#15]
Im using the api to create a new client. but i got an exception that tells me the email is invalid and i dont know why ????
`  public function getSellsyApi() {

    $guzzleClient = new \GuzzleHttp\Client();

     //Create the transport bridge
    $transportBridge = new \Teknoo\Sellsy\Transport\Guzzle($guzzleClient);

     //Create the front object
      $sellsy = new \Teknoo\Sellsy\Sellsy(
      'https://apifeed.sellsy.com/0/',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      );

      $sellsy->setTransport($transportBridge);

      return $sellsy ;

  }

    public function createSellsyCustomer($params = [],$type = 'person') {

    extract($params);
    $fullName = "$lastname $firstname";

    $sellsy = $this->getSellsyApi();
    $Client = $sellsy->Client()
                     ->create(['third' => ['name' => $fullName,'type' => $type, 'tags' => 'Company','auxcode'  => 'Company'],
                               'contact' => ['name' => $lastname, 'forename' => $firstname,'email' => $email ],
                               'address' => $address
                              ])
                      ->getResponse();

    return $Client;

  }`

i got an error email is invalid the email is Madan062@company.com.

is there some restrictions on email on sellsy ? 

thanks
![Sans titre](https://user-images.githubusercontent.com/44771382/55318769-d69b8780-5473-11e9-8b9c-cbaf3417f9f7.jpg)

**Comment by frenchcomp** [comment]
Sorry, this library is independant. I does not work with Sellsy. I invite you to contact them directly.

**Comment by aguerin** [comment]
Hi @Ericdev89, I use this client too, and didn't have any trouble of creating a new client with the @mail you've indicated above

**Comment by frenchcomp** [comment]
Thanks for this feedback @aguerin :)

I close this issue because it is not related to this library.
