### ISSUE TITLE
Error, the Accountdatas has been not found

### ISSUE THREAD

**Issue by kalfeutre** [UniAlteri/sellsy-client#17]
Hi,
I have an issue with the Accountdatas methods when i use it on the online server.
When i use on localhost i can fetch the results from this method ( for exemple ) :

Accountdatas()->getTranslationLanguages()->getResponse()

But on the server, i catch this error : 

```
Type: DomainException

Message: Error, the Accountdatas has been not found

Filename:  app/application/vendor/teknoo/sellsy-client/src/Sellsy.php

Line Number: 201
```
Of course i guess it"s from the domain, but i don't understand exactly where this bug can come from ( cause other methods as Stock, Document, Client... works fine )

Thanks a lot for your help !

**Comment by kalfeutre** [comment]
Just found the mistake i made ( put a d lowercase instead of uppercase to AccountDatas ). My bet !

**Comment by frenchcomp** [comment]
No problem
Have a nice day
