### ISSUE TITLE
how can i update cataloge or get list of catalouge no proper doc !!

### ISSUE THREAD

**Issue by pratikraman-dev** [UniAlteri/sellsy-client#20]

**Comment by frenchcomp** [comment]
Hi @pratt1305 
This library is independant of Sellsy company and is only a client, **developed for free on my weeks ends** !

Requests follows the Sellsy API, by example in the README File, in the current stable version (2.x  branch), to call the Sellsy's method "Infos.getInfos" : 
```
$result = $sellsy->Infos()->getInfos()->getResponse();
echo $result['consumerdatas']['id'];
```

To pass a parameter, by example to "Accountdatas.createTaxe"
```
$sellsy->Accountdatas()->createTaxe(['taxe' => array(
            'name'      => {{name}},
            'value'     => {{taxe_value}},
            'isEnabled' => {{taxe_enabled}}
        )]);
```
