### ISSUE TITLE
How to Upload image in product !!

### ISSUE THREAD

**Issue by pratikraman-dev** [UniAlteri/sellsy-client#21]
Unable to find proper doc or example for file upload please help !!!

**Comment by frenchcomp** [comment]
Hi..
For the second time : This library is a free and independant client ! The documentation relates only to the use of the client not of the Sellsy service.

I am not a support about Sellsy. And Sellsy already provides a complete documentation here : https://api.sellsy.com/documentation/methods Please to use it ! 

Usually the images are passed as a method parameter, like another parameter, encoded in base 64 or in url.

To finish : **The politeness is not an option here** 

Richard.
