### ISSUE TITLE
doctype is invalid

### ISSUE THREAD

**Issue by MatthieuMan** [UniAlteri/sellsy-client#29]
```php
$payload = [
            'method' => 'Document.sendDocByMail',
            'params' => [
                'docid' => 20791894,
                'email' => [
                    'doctype' => 'invoice',
                    'emails' => ["test@test.com", "tests@test.com"]
                ]
            ]
        ];
$sellsyClient->Document()->sendDocByMail($payload);
```
keeps tellming me that `message: "doctype is invalid"`

**Comment by frenchcomp** [comment]
Hi,
This error is thrown by the Sellsy API, it is not an error from the client. I invite you to check the sellsy api documentation :
This client is only compatible with the V1 of the sellsy api : https://api.sellsy.fr/documentation/methodes.
(The client encodes only your paylod in the body request)

This library is independant from Sellsy.
