### ISSUE TITLE
Manage rate limit

### ISSUE THREAD

**Issue by juherr** [UniAlteri/sellsy-client#30]
Sellsy limits (by default at least) 5 req / sec and the client should be able to manage it.

As example, we are currently doing something like.

```php
$start = microtime(true);
foreach ($items as $i => $item) {
    if ($i % 5 === 0) {
        $stop = microtime(true);
        $sleep = 1000000 - intval(($stop - $start) * 1000000);
        if ($sleep > 0) {
            usleep($sleep);
        }
        $start = microtime(true);
    }
    $addresses = $client->Client()->getOne([
        'clientid' => $item['thirdid'],
    ])->getResponse()['address'];
    // ...
}
```

**Comment by frenchcomp** [comment]
Sorry but it's not a behaviour to include in the client : This must be directly managed by the developper using the client.
I can't force an implementation for all users of this library.

By example, your example can crash very quickly a webserver. (In sleep/usleep, the PHP process is freeze and can not execute another stuff. The count of php process is limited on PHP-FPM.) If an async behavior is used (like reactphp or fibers), sleep/usleep will block other requests / operations.

There are some ways to manage this issue : 
* Do not call to sellsy directly in your webpage, but in a worker running in background (like a cron or a system daemon)
* Use your own client class. You can extends the lib's client class, override the `promise` method and use it into the Sellsy class thanks to the method `setClient`.

**Comment by juherr** [comment]
Thanks for the feedback.

For the record, I managed it with a naive `Transport` implementation:

```php
class RateLimitTransport implements TransportInterface
{
    public const RATE_LIMIT = 5;
    private int $cnt;
    private float $time;

    public function __construct(
        private readonly TransportInterface $transport,
    )
    {
        $this->cnt = 0;
        $this->time = microtime(true);
    }

    public function createRequest(string $method, $uri): RequestInterface
    {
        return $this->transport->createRequest($method, $uri);
    }

    public function createStream(array &$elements, ?RequestInterface $request = null): StreamInterface
    {
        return $this->transport->createStream($elements, $request);
    }

    public function asyncExecute(RequestInterface $request): PromiseInterface
    {
        $this->cnt++;
        if ($this->cnt === self::RATE_LIMIT) {
            $stop = microtime(true);
            $sleep = 1000000 - intval(($stop - $this->time) * 1000000);
            if ($sleep > 0) {
                usleep($sleep);
            }
            $this->time = microtime(true);
            $this->cnt = 0;
        }
        return $this->transport->asyncExecute($request);
    }

    public function createUri(string $uri = ''): UriInterface
    {
        return $this->transport->createUri($uri);
    }
}
```

**Comment by frenchcomp** [comment]
Thanks you. You can make a PR to update the documentation of this library and include your example in a new section if you wish.
