### ISSUE TITLE
How to use this library ?

### ISSUE THREAD

**Issue by apsylone** [UniAlteri/sellsy-client#7]
I've tried so far creating a new Sellsy object, calling methods on it ; but the Result is always empty.
I've no errors, no exceptions thrown ...

Thanks for the lights !

**Comment by frenchcomp** [comment]
Sorry, the version in master is a beta. I wait a test account from Sellsy but I have no more news, so I can not test and work on this library. The first version still working. I hope work on the version 2.0 in 2018.

**Comment by apsylone** [comment]
I have a test account if you would like I can share it with you.

**Comment by frenchcomp** [comment]
Thanks, can you contact me at richarddeloge@gmail.com ?
Thanks :)
