### ISSUE TITLE
Documentation not working with published version

### ISSUE THREAD

**Issue by IfnotFr** [UniAlteri/sellsy-client#8]
Hi !

Actually your published version on composer is your 1.0 branch. Whereas your documentaiton refer to your master branch.

So instead of installing with `composer require teknoo/sellsy-client` i had to install with adding `dev-master`. This is not a stable solution, so i guess you will need to publish your lastest modifications into a stable version with the api your specified on your github !

Thanks :)

**Comment by frenchcomp** [comment]
Hi, 
The version available on master is in beta. You can list available versions in the panel "Release" on github, or on packagist. So you can set your required version on "^2.0.0-beta2".
For more help, I invite you to consult the help of composer / packagist : https://getcomposer.org/doc/ :)
